# Generated by Django 3.0 on 2023-04-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praticiene',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(max_length=1000),
        ),
    ]
