# Generated by Django 3.2 on 2023-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioApp', '0003_message_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='praticiene',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
